### ISSUE TITLE
[Upgrade] deploy changes from program.json - Thurs 7/8

### ISSUE THREAD

**Issue by lisaattrillium** [Trillium-Solutions/rideconnection-program-finder#5]
CC @christrillium @arr0nax 

Bill To: RideConnection - Metro Pilot 
- The final Invoice is due Wed 7/7. TRY to do billable hours by Wed lunchtime.
- Chris will be OOO on Wed 7/7 but is available for questions. Only he & Nome worked on this project.

Max Hours: 2-5

To Do
- [ ] get cozy with the docs
- [ ] deploy
- [ ] update README.md since deployment is not automatic like we thought

**In email from Chris 6/30:**

> I recently made a few commits in the programs.json file of Ride Connections Program finder (Github). I updated a couple URLs. 

> I edited programs.json directly in Github. On the repo homepage it says that the latest release is automatically deployed. Does that mean that the production program finder should be auto updated at certain intervals?

**Annie's Response**

> I'm not familiar with applet deployments, but looking at it now I don't think it's automatically updated. In ansible (https://github.com/Trillium-Solutions/ansible/blob/master/playbooks/applet/applet.yml) it looks like it's versioned similar to how GTFSM is, we'd need to create a new branch/version, and likely just run this playbook to update it. 

>If Chris has a timeline for when these updates need to be live we can schedule an upgrade time -- but at least a day or two for us to double-check our understanding of the applet deployments and make sure we're doing things correctly would be ideal! I've never done anything with applets before but with how it's set up in ansible it shouldn't be too difficult (fingers crossed).

**Clayton's Response**

> I am also unfamiliar with this particular applet - but applets can be deployed at any time. The production versions are duplicated, so there is no downtime when upgrading.

**Comment by arr0nax** [comment]
@anniekfifer if you want any more info about applet deployment, I am happy to share what I know!

**Comment by lisaattrillium** [comment]
@arr0nax @anniekfifer I'll leave it to yall to select a time for the deployment on Thurs 7/8!

**Comment by anniekfifer** [comment]
>The final Invoice is due Wed 7/7. TRY to do billable hours by Wed lunchtime.

@lisaattrillium I'm interpreting this as "do any prep work before wed lunch, but perform the actual update on thursday", is that correct?

**Comment by christrillium** [comment]
@anniekfifer you got it

**Comment by anniekfifer** [comment]
@christrillium updated!

https://rc-program-finder.trilliumtransit.com/rc-program-finder/js/

Confirmed that the url for Tualatin Shuttle has updated to https://rideconnection.org/assets/pdf/RC-tualatin-05112021.pdf when searching programs for Tualatin Community Park

**Comment by christrillium** [comment]
Thanks so much @anniekfifer!

**Comment by lisaattrillium** [comment]
@anniekfifer what point label should this be?

**Comment by anniekfifer** [comment]
>@anniekfifer what point label should this be?

point_small is good!
